# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_case_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='case',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Case'),
        ),
    ]
